import type { FormEvent } from "react";

export interface CharacterSummary { character_id: string; system: string; name: string; source_type: string; sheet_data: Record<string, unknown>; updated_at: string | null; }

interface CharacterLibraryPanelProps { characters: CharacterSummary[]; name: string; stText: string; selectedCharacterId: string | null; onClose: () => void; onNameChange: (value: string) => void; onStTextChange: (value: string) => void; onImportSt: (event: FormEvent) => void; onSelect: (characterId: string) => void; onDelete: (characterId: string) => void; }

export function CharacterLibraryPanel(props: CharacterLibraryPanelProps) {
  const selected = props.characters.find((character) => character.character_id === props.selectedCharacterId);
  const attributes = selected?.sheet_data.attributes as Record<string, number> | undefined;
  const skills = selected?.sheet_data.skills as Record<string, number> | undefined;
  return <div className="knowledge-manager-backdrop" role="presentation" onMouseDown={props.onClose}><section className="knowledge-manager character-library-manager" role="dialog" aria-modal="true" aria-label="我的角色库" onMouseDown={(event) => event.stopPropagation()}><header className="knowledge-manager-header"><div><span className="eyebrow">COC-STAR / CHARACTERS</span><h2>我的角色库</h2><p>角色卡保存在首页，进入不同房间时可以重复加载；房间内状态不会覆盖原始角色卡。</p></div><button type="button" className="drawer-close" onClick={props.onClose} aria-label="关闭角色库">×</button></header><div className="knowledge-manager-body"><aside className="knowledge-manager-sidebar"><form className="ai-form" onSubmit={props.onImportSt}><input placeholder="角色名称" value={props.name} onChange={(event) => props.onNameChange(event.target.value)} required /><textarea rows={9} placeholder="粘贴骰娘 .st 文本，例如：力量70str70侦查25" value={props.stText} onChange={(event) => props.onStTextChange(event.target.value)} required /><button type="submit" className="primary-action">导入 .st 角色卡</button></form><div className="knowledge-base-list">{props.characters.map((character) => <button type="button" key={character.character_id} className={character.character_id === props.selectedCharacterId ? "knowledge-base-item active" : "knowledge-base-item"} onClick={() => props.onSelect(character.character_id)}><strong>{character.name}</strong><small>{character.system.toUpperCase()} · {character.source_type}</small></button>)}{props.characters.length === 0 && <p className="drawer-hint">还没有角色卡，可以先粘贴骰娘 .st 文本导入。</p>}</div></aside><section className="knowledge-manager-editor">{selected ? <><div className="knowledge-editor-heading"><div><span className="eyebrow">CHARACTER SHEET</span><h3>{selected.name}</h3></div><button type="button" className="text-action" onClick={() => props.onDelete(selected.character_id)}>删除角色</button></div><div className="character-stat-grid">{Object.entries(attributes ?? {}).map(([key, value]) => <div className="character-stat-card" key={key}><small>{key.toUpperCase()}</small><strong>{value}</strong><span>半值 {Math.floor(value / 2)} · 极难 {Math.floor(value / 5)}</span></div>)}</div><section className="character-skill-preview"><div className="drawer-section-heading"><span>技能</span><small>{Object.keys(skills ?? {}).length} 项</small></div><div className="character-skill-list">{Object.entries(skills ?? {}).map(([key, value]) => <span key={key}>{key} {value}</span>)}</div></section></> : <div className="knowledge-manager-empty"><span className="knowledge-icon">✦</span><h3>选择一张角色卡</h3><p>导入后可以在这里检查属性与技能，后续再完善完整角色卡编辑器。</p></div>}</section></div></section></div>;
}
