import type { FormEvent } from "react";

export interface AiProviderSummary { provider_id: string; name: string; provider_type: string; base_url: string; model: string; api_key_masked: string; enabled: boolean; }
export interface KnowledgeBaseSummary { knowledge_base_id: string; parent_id?: string | null; name: string; description: string; kind: "knowledge" | "documents"; document_count: number; }
export interface KnowledgeDocumentSummary { document_id: string; knowledge_base_id: string; title: string; content: string; category: string; source_type?: string; source_name?: string | null; mime_type?: string | null; ai_enabled?: boolean; }
export interface RoomAiConfig { room_id: string | null; provider_id: string | null; enabled: boolean; assistant_name: string; system_prompt: string; avatar_url: string | null; trigger_mode: "mention" | "main_channel" | "all"; scene_context_enabled: boolean; knowledge_base_ids: string[]; }
export interface AiLogSummary { log_id: string; event_type: string; status: string; request_summary: string; response_summary: string; latency_ms: number | null; created_at: string | null; }

interface RoomAiPanelProps { config: RoomAiConfig; providers: AiProviderSummary[]; logs: AiLogSummary[]; providerName: string; providerBaseUrl: string; providerModel: string; providerApiKey: string; onConfigChange: (config: RoomAiConfig) => void; onProviderNameChange: (value: string) => void; onProviderBaseUrlChange: (value: string) => void; onProviderModelChange: (value: string) => void; onProviderApiKeyChange: (value: string) => void; onSaveConfig: (event: FormEvent) => void; onSaveProvider: (event: FormEvent) => void; }

export function RoomAiPanel(props: RoomAiPanelProps) {
  const { config, providers, logs } = props;
  return <div className="ai-panel">
    <section className="ai-panel-section"><div className="drawer-section-heading"><span>房间 AI 助手</span><span className={config.enabled ? "ai-status ai-status-on" : "ai-status"}>{config.enabled ? "运行中" : "未启用"}</span></div><form className="ai-form" onSubmit={props.onSaveConfig}><label>助手名称<input value={config.assistant_name} onChange={(event) => props.onConfigChange({ ...config, assistant_name: event.target.value })} maxLength={80} /></label><label>触发方式<select value={config.trigger_mode} onChange={(event) => props.onConfigChange({ ...config, trigger_mode: event.target.value as RoomAiConfig["trigger_mode"] })}><option value="mention">@提及或 #指令</option><option value="main_channel">主频道每条发言</option><option value="all">所有频道每条发言</option></select></label><label>助手立绘 URL<input value={config.avatar_url ?? ""} onChange={(event) => props.onConfigChange({ ...config, avatar_url: event.target.value || null })} placeholder="可选" /></label><label>人格提示词<textarea rows={5} value={config.system_prompt} onChange={(event) => props.onConfigChange({ ...config, system_prompt: event.target.value })} /></label><label className="ai-check"><input type="checkbox" checked={config.scene_context_enabled} onChange={(event) => props.onConfigChange({ ...config, scene_context_enabled: event.target.checked })} />把当前场景作为上下文</label><label className="ai-check"><input type="checkbox" checked={config.enabled} onChange={(event) => props.onConfigChange({ ...config, enabled: event.target.checked })} />启用房间 AI</label><label>使用厂商<select value={config.provider_id ?? ""} onChange={(event) => props.onConfigChange({ ...config, provider_id: event.target.value || null })}><option value="">未选择</option>{providers.map((provider) => <option key={provider.provider_id} value={provider.provider_id}>{provider.name} · {provider.model}</option>)}</select></label><p className="drawer-hint">知识库挂载请在“房间知识库”中单独设置。AI 只读取当前房间已挂载且允许参与 AI 的文档。</p><button type="submit" className="primary-action">保存房间 AI 配置</button></form></section>
    <section className="ai-panel-section"><div className="drawer-section-heading"><span>厂商配置</span><small>API Key 只在服务端保存</small></div><form className="ai-form" onSubmit={props.onSaveProvider}><input placeholder="配置名称" value={props.providerName} onChange={(event) => props.onProviderNameChange(event.target.value)} required /><input placeholder="兼容接口地址，如 https://api.example.com/v1" value={props.providerBaseUrl} onChange={(event) => props.onProviderBaseUrlChange(event.target.value)} required /><input placeholder="模型名称" value={props.providerModel} onChange={(event) => props.onProviderModelChange(event.target.value)} required /><input type="password" placeholder="API Key" value={props.providerApiKey} onChange={(event) => props.onProviderApiKeyChange(event.target.value)} required /><button type="submit" className="secondary-action">保存厂商</button></form><div className="ai-provider-list">{providers.map((provider) => <div key={provider.provider_id}><strong>{provider.name}</strong><small>{provider.model} · {provider.api_key_masked}</small></div>)}</div></section>
    <section className="ai-panel-section"><div className="drawer-section-heading"><span>运行日志</span><small>最近 {logs.length} 条</small></div><div className="ai-log-list">{logs.slice(0, 20).map((log) => <div className="ai-log-row" key={log.log_id}><span className={`ai-log-status ai-log-${log.status}`}>{log.status}</span><div><strong>{log.event_type}</strong><small>{log.request_summary || "无请求摘要"}</small></div><em>{log.latency_ms ?? "—"} ms</em></div>)}{logs.length === 0 && <p className="drawer-hint">还没有 AI 运行记录。</p>}</div></section>
  </div>;
}
